export type Category = {
  name: string;
  slug: string;
};

export type Categories = Category[];

export const default_categories: Categories = [
  { name: 'World News', slug: 'world-news' },
  { name: 'U.S. News', slug: 'us-news' },
  { name: 'Business', slug: 'business' },
  { name: 'Technology', slug: 'technology' },
  { name: 'Entertainment', slug: 'entertainment' },
  { name: 'Sports', slug: 'sports' },
  { name: 'Health', slug: 'health' },
  { name: 'Science', slug: 'science' },
  { name: 'Education', slug: 'education' },
  { name: 'Politics', slug: 'politics' },
  { name: 'Environment', slug: 'environment' },
  { name: 'Weather', slug: 'weather' },
  { name: 'Crime', slug: 'crime' },
  { name: 'Religion', slug: 'religion' },
  { name: 'Travel', slug: 'travel' },
  { name: 'Food', slug: 'food' },
  { name: 'Arts', slug: 'arts' },
  { name: 'Fashion', slug: 'fashion' },
  { name: 'Music', slug: 'music' },
  { name: 'Movies', slug: 'movies' },
  { name: 'TV', slug: 'tv' },
  { name: 'Books', slug: 'books' },
  { name: 'Automotive', slug: 'automotive' },
  { name: 'Real Estate', slug: 'real-estate' },
  { name: 'Personal Finance', slug: 'personal-finance' },
  { name: 'Stocks', slug: 'stocks' },
  { name: 'Cryptocurrency', slug: 'cryptocurrency' },
  { name: 'Gaming', slug: 'gaming' },
  { name: 'Social Media', slug: 'social-media' },
  { name: 'Celebrities', slug: 'celebrities' },
  { name: 'Fitness', slug: 'fitness' },
  { name: 'Beauty', slug: 'beauty' },
  { name: 'Pets', slug: 'pets' },
  { name: 'DIY', slug: 'diy' },
  { name: 'Family', slug: 'family' },
  { name: 'Parenting', slug: 'parenting' },
  { name: 'Military', slug: 'military' },
  { name: 'Aviation', slug: 'aviation' },
  { name: 'Space', slug: 'space' },
  { name: 'Energy', slug: 'energy' },
  { name: 'Transportation', slug: 'transportation' },
  { name: 'Artificial Intelligence', slug: 'artificial-intelligence' },
  { name: 'Social Issues', slug: 'social-issues' },
  { name: 'History', slug: 'history' },
  { name: 'Psychology', slug: 'psychology' },
  { name: 'Philosophy', slug: 'philosophy' },
  { name: 'Art', slug: 'art' },
  { name: 'Design', slug: 'design' },
  { name: 'Architecture', slug: 'architecture' },
  { name: 'Engineering', slug: 'engineering' },
];
